name: ezyhr_mobile_apps
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.5+39

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # another_flushbar: ^1.10.28
  # carousel_slider: ^4.0.0
  # equatable: ^2.0.3
  # flutter_bloc: ^8.0.1
  # flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  # url_launcher: ^6.1.11
  # app_settings: ^5.1.1
  # cached_network_image: ^3.2.0
  camera: ^0.11.0+1
  currency_text_input_formatter: ^2.1.5
  # dart_ipify: ^1.1.1
  # device_info_plus: ^9.1.1
  dio: ^5.1.0
  flutter_svg: ^2.0.4
  form_field_validator: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: ^4.6.1
  get_storage: ^2.0.3
  # image_gallery_saver: ^2.0.3
  # onesignal_flutter: ^5.0.4
  package_info_plus: ^8.0.0
  path_provider: ^2.0.8
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.12
  timezone: ^0.9.2
  uuid: ^4.2.2
  overlay_support: ^2.0.1
  flutter_typeahead: ^5.0.1
  # flutter_image_compress: ^2.1.0
  file_picker: ^8.0.5
  flutter_dotenv: ^5.0.2
  # getxbottombar: ^0.0.1
  #wakelock: ^0.6.2
  # table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^26.1.38
  shimmer: ^3.0.0
  local_auth: ^2.1.7
  webview_flutter: ^4.4.2
  # google_ml_kit: 0.12.0
  # firebase_core: ^1.6.0
  # firebase_messaging: ^10.0.9
  # google_mlkit_face_detection: ^0.9.0
  # tflite_flutter: ^0.10.4
  image: ^4.2.0
  currency_picker: ^2.0.20
  country_picker: ^2.0.23
  # onesignal_flutter: ^5.2.1
  onesignal_flutter: ^5.3.0
  syncfusion_flutter_calendar: ^26.1.38
  table_calendar: ^3.0.9
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.1
  win32: ^5.5.1
  google_mlkit_face_detection: ^0.12.0
  # google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/v2/bottom_menu/
    - assets/v2/home_screen/
    - assets/v2/reimbursement/

    # - assets/mobilefacenet.tflite
    # - assets/models/
    # - assets/models/mobile_facenet.tflite
